apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc2
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gce-storage-class
  resources:
    requests:
      storage: 450Mi
